### ISSUE TITLE
[FEATURE] dashscope-embedding-model dimensions

### ISSUE THREAD

**Issue by zundaren** [langchain4j/langchain4j-community#105]
There is no place to set dimensions

**Comment by zundaren** [comment]
> [@zundaren](https://github.com/zundaren) Can you elaborate a bit more on why you want to set dimension?

open-ai has this parameter langchain4j.open-ai.embedding-model.dimensions

I used text-embedding-v3 and the default EmbeddingStore<TextSegment> when using the vector model to cut the content, an error was reported, vector 384 is not equal to 1024, I was wondering whether to set the dimensions of the model

**Comment by Martin7-1** [comment]
What model and embedding store are you using? Do you have any detailed exception stacktrace?

The error may occur when you set wrong dimension parameter in `EmbeddinStore` rather than the embedding model, all embedding models in dashscope have their own dimension setting (It is a model configuration rather than manual setting). In `langchain4j-community-dashscope`, the dimension is actually set by embed 'test' in following code:

```java
    public int dimension() {
        if (this.dimension != null) {
            return this.dimension;
        } else {
            Integer knownDimension = this.knownDimension();
            this.dimension = (Integer)Optional.ofNullable(knownDimension).orElseGet(() -> ((Embedding)this.embed("test").content()).dimension());
            return this.dimension;
        }
    }
```

So, I think the exception you encounter may be on EmbeddingStore's side, could you please share more logs?

**Comment by zundaren** [comment]
> What model and embedding store are you using? Do you have any detailed exception stacktrace?
> 
> The error may occur when you set wrong dimension parameter in `EmbeddinStore` rather than the embedding model, all embedding models in dashscope have their own dimension setting (It is a model configuration rather than manual setting). In `langchain4j-community-dashscope`, the dimension is actually set by embed 'test' in following code:
> 
>     public int dimension() {
>         if (this.dimension != null) {
>             return this.dimension;
>         } else {
>             Integer knownDimension = this.knownDimension();
>             this.dimension = (Integer)Optional.ofNullable(knownDimension).orElseGet(() -> ((Embedding)this.embed("test").content()).dimension());
>             return this.dimension;
>         }
>     }
> So, I think the exception you encounter may be on EmbeddingStore's side, could you please share more logs?

```
 package com.cl.tpl.controller;

import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.cl.tpl.service.ChatService;

import cn.hutool.core.util.IdUtil;
import dev.langchain4j.data.document.Document;
import dev.langchain4j.data.document.loader.FileSystemDocumentLoader;
import dev.langchain4j.data.document.splitter.DocumentByLineSplitter;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.store.embedding.EmbeddingStoreIngestor;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Resource;
import reactor.core.publisher.Flux;

@RestController
@RequestMapping("/test")
public class ChatController {

    @Resource
    ChatService chatService;

    @Autowired(required = false)
    EmbeddingModel embeddingModel;
    @Autowired(required = false)
    EmbeddingStore<TextSegment> embeddingStore;


    private static final ExecutorService EXECUTOR = Executors.newFixedThreadPool(2);


    @GetMapping("load")
    public Object load() {
        List<Document> documents =
                FileSystemDocumentLoader.loadDocuments("D:\\ideaworkspace3\\springtpl\\ai-service\\src\\main\\resources\\doc");

        // 远程计算
        EmbeddingStoreIngestor embeddedStoreIngestor = EmbeddingStoreIngestor.builder()
                .embeddingStore(embeddingStore)
                .embeddingModel(embeddingModel)
                .documentSplitter(new DocumentByLineSplitter(20, 10)) // 最大切割token和重叠token
                .build();

        embeddedStoreIngestor.ingest(documents);

        return "ok";
    }

    @GetMapping("/ai")
    public Object ai(@RequestParam String req) {
        Flux<String> flux = chatService.chat2(IdUtil.fastUUID(), req);
        flux.subscribe(s -> {
            System.out.print(s);
        });

        return "success";
    }

}

```

```
package com.cl.tpl.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.context.annotation.Bean;

import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.memory.chat.MessageWindowChatMemory;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.chat.StreamingChatLanguageModel;
import dev.langchain4j.model.chat.listener.ChatModelErrorContext;
import dev.langchain4j.model.chat.listener.ChatModelListener;
import dev.langchain4j.model.chat.listener.ChatModelRequestContext;
import dev.langchain4j.model.chat.listener.ChatModelResponseContext;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.model.embedding.onnx.allminilml6v2q.AllMiniLmL6V2QuantizedEmbeddingModel;
import dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever;
import dev.langchain4j.service.AiServices;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.web.search.WebSearchTool;
import dev.langchain4j.web.search.searchapi.SearchApiWebSearchEngine;
import jakarta.annotation.Resource;

@AutoConfiguration
public class Config {

    @Resource
    StreamingChatLanguageModel streamingChatLanguageModel;
    @Resource
    ChatLanguageModel languageModel;
    @Resource
    RedisMessageStore messageStore;

    @Autowired(required = false)
    EmbeddingModel embeddingModel;
    @Autowired(required = false)
    EmbeddingStore<TextSegment> embeddingStore;

    @Bean
    public ChatService chatServiceRemote() {
        SearchApiWebSearchEngine searchEngine = SearchApiWebSearchEngine.builder()
                .apiKey("1").engine("bing").build();
        WebSearchTool webTool = WebSearchTool.from(searchEngine);

        ChatService service = AiServices.builder(ChatService.class)
                .chatLanguageModel(languageModel)
                .streamingChatLanguageModel(streamingChatLanguageModel)
                .tools(new ITool(), webTool)
                .chatMemoryProvider(memoryId -> {
                    return MessageWindowChatMemory.builder().id(memoryId).chatMemoryStore(messageStore).maxMessages(10).build();
                })
                .contentRetriever(EmbeddingStoreContentRetriever.builder()
                        .embeddingModel(embeddingModel)
                        .embeddingStore(embeddingStore).build()
                ) // 向量搜索存储
                .systemMessageProvider(o -> {
                    return "你是一个后端程序员";
                }).build();

        return service;
    }
}

```

```
langchain4j:
  open-ai:
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: sk
#      model-name: deepseek-chat
#      log-requests: true
#      log-responses: true
#    streaming-chat-model:
#      base-url: https://api.deepseek.com
#      api-key: sk
#      model-name: deepseek-chat
#      log-requests: true
#      log-responses: true
#    embedding-model:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      api-key: sk
#      model-name: text-embedding-v3
#      dimensions: 256

  community:
    dashscope:
      chat-model:
        api-key: sk-
        model-name: qwen-plus
        log-requests: true
        log-responses: true
      streaming-chat-model:
        api-key: sk-
        model-name: qwen-plus
        log-requests: true
        log-responses: true
      embedding-model:
        base-url: https://dashscope.aliyuncs.com/api/v1
        api-key: sk-
        model-name: text-embedding-v3

    redis:
      enabled: false
      host: 0.0.0.0
      port: 6379
      password: 1111
      dimension: 384
```
